package com.john.silverfox.dal.mybatis.mapper;

import com.john.silverfox.dal.mybatis.model.Balance;
import com.john.silverfox.dal.mybatis.model.BalanceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BalanceMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table balance
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	int countByExample(BalanceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table balance
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	int deleteByExample(BalanceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table balance
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table balance
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	int insert(Balance record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table balance
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	int insertSelective(Balance record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table balance
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	List<Balance> selectByExample(BalanceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table balance
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	Balance selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table balance
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	int updateByExampleSelective(@Param("record") Balance record, @Param("example") BalanceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table balance
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	int updateByExample(@Param("record") Balance record, @Param("example") BalanceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table balance
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	int updateByPrimaryKeySelective(Balance record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table balance
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	int updateByPrimaryKey(Balance record);
}