package com.john.silverfox.dal.mybatis.mapper;

import com.john.silverfox.dal.mybatis.model.MyStrategy;
import com.john.silverfox.dal.mybatis.model.MyStrategyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MyStrategyMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_strategies
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	int countByExample(MyStrategyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_strategies
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	int deleteByExample(MyStrategyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_strategies
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_strategies
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	int insert(MyStrategy record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_strategies
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	int insertSelective(MyStrategy record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_strategies
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	List<MyStrategy> selectByExample(MyStrategyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_strategies
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	MyStrategy selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_strategies
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	int updateByExampleSelective(@Param("record") MyStrategy record, @Param("example") MyStrategyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_strategies
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	int updateByExample(@Param("record") MyStrategy record, @Param("example") MyStrategyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_strategies
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	int updateByPrimaryKeySelective(MyStrategy record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_strategies
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	int updateByPrimaryKey(MyStrategy record);
}