package com.john.silverfox.dal.mybatis.mapper;

import com.john.silverfox.dal.mybatis.model.Strategy;
import com.john.silverfox.dal.mybatis.model.StrategyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StrategyMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strategies
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	int countByExample(StrategyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strategies
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	int deleteByExample(StrategyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strategies
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strategies
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	int insert(Strategy record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strategies
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	int insertSelective(Strategy record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strategies
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	List<Strategy> selectByExample(StrategyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strategies
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	Strategy selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strategies
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	int updateByExampleSelective(@Param("record") Strategy record, @Param("example") StrategyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strategies
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	int updateByExample(@Param("record") Strategy record, @Param("example") StrategyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strategies
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	int updateByPrimaryKeySelective(Strategy record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strategies
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	int updateByPrimaryKey(Strategy record);
}