package com.john.silverfox.dal.mybatis.mapper;

import com.john.silverfox.dal.mybatis.model.TickRecord;
import com.john.silverfox.dal.mybatis.model.TickRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TickRecordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tick_records
	 * @mbggenerated  Sun Jun 24 23:31:22 CST 2018
	 */
	int countByExample(TickRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tick_records
	 * @mbggenerated  Sun Jun 24 23:31:22 CST 2018
	 */
	int deleteByExample(TickRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tick_records
	 * @mbggenerated  Sun Jun 24 23:31:22 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tick_records
	 * @mbggenerated  Sun Jun 24 23:31:22 CST 2018
	 */
	int insert(TickRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tick_records
	 * @mbggenerated  Sun Jun 24 23:31:22 CST 2018
	 */
	int insertSelective(TickRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tick_records
	 * @mbggenerated  Sun Jun 24 23:31:22 CST 2018
	 */
	List<TickRecord> selectByExample(TickRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tick_records
	 * @mbggenerated  Sun Jun 24 23:31:22 CST 2018
	 */
	TickRecord selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tick_records
	 * @mbggenerated  Sun Jun 24 23:31:22 CST 2018
	 */
	int updateByExampleSelective(@Param("record") TickRecord record, @Param("example") TickRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tick_records
	 * @mbggenerated  Sun Jun 24 23:31:22 CST 2018
	 */
	int updateByExample(@Param("record") TickRecord record, @Param("example") TickRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tick_records
	 * @mbggenerated  Sun Jun 24 23:31:22 CST 2018
	 */
	int updateByPrimaryKeySelective(TickRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tick_records
	 * @mbggenerated  Sun Jun 24 23:31:22 CST 2018
	 */
	int updateByPrimaryKey(TickRecord record);
	
	List<TickRecord> selectAfterTick(@Param("currencyPair") String currencyPair,
			@Param("exchangeId") Integer exchangeId, @Param("tick") String tick, @Param("maxCounts") Integer maxCounts);
}