package com.john.silverfox.dal.mybatis.mapper;

import com.john.silverfox.dal.mybatis.model.ToTick;
import com.john.silverfox.dal.mybatis.model.ToTickExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ToTickMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table to_ticks
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	int countByExample(ToTickExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table to_ticks
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	int deleteByExample(ToTickExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table to_ticks
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table to_ticks
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	int insert(ToTick record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table to_ticks
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	int insertSelective(ToTick record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table to_ticks
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	List<ToTick> selectByExample(ToTickExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table to_ticks
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	ToTick selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table to_ticks
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	int updateByExampleSelective(@Param("record") ToTick record, @Param("example") ToTickExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table to_ticks
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	int updateByExample(@Param("record") ToTick record, @Param("example") ToTickExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table to_ticks
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	int updateByPrimaryKeySelective(ToTick record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table to_ticks
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	int updateByPrimaryKey(ToTick record);
}