package com.john.silverfox.dal.mybatis.mapper;

import com.john.silverfox.dal.mybatis.model.Transaction;
import com.john.silverfox.dal.mybatis.model.TransactionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TransactionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table transactions
	 * @mbggenerated  Sun Jun 24 23:11:35 CST 2018
	 */
	int countByExample(TransactionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table transactions
	 * @mbggenerated  Sun Jun 24 23:11:35 CST 2018
	 */
	int deleteByExample(TransactionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table transactions
	 * @mbggenerated  Sun Jun 24 23:11:35 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table transactions
	 * @mbggenerated  Sun Jun 24 23:11:35 CST 2018
	 */
	int insert(Transaction record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table transactions
	 * @mbggenerated  Sun Jun 24 23:11:35 CST 2018
	 */
	int insertSelective(Transaction record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table transactions
	 * @mbggenerated  Sun Jun 24 23:11:35 CST 2018
	 */
	List<Transaction> selectByExample(TransactionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table transactions
	 * @mbggenerated  Sun Jun 24 23:11:35 CST 2018
	 */
	Transaction selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table transactions
	 * @mbggenerated  Sun Jun 24 23:11:35 CST 2018
	 */
	int updateByExampleSelective(@Param("record") Transaction record, @Param("example") TransactionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table transactions
	 * @mbggenerated  Sun Jun 24 23:11:35 CST 2018
	 */
	int updateByExample(@Param("record") Transaction record, @Param("example") TransactionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table transactions
	 * @mbggenerated  Sun Jun 24 23:11:35 CST 2018
	 */
	int updateByPrimaryKeySelective(Transaction record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table transactions
	 * @mbggenerated  Sun Jun 24 23:11:35 CST 2018
	 */
	int updateByPrimaryKey(Transaction record);

	Transaction selectLastByType(@Param("accountId") Long accountId, 
			@Param("currencyPair") String currencyPair, @Param("type") Integer type);
}



