package com.john.silverfox.dal.mybatis.model;

import java.util.Date;

public class Account {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.id
     *
     * @mbggenerated Sun Jun 24 23:40:44 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.user_id
     *
     * @mbggenerated Sun Jun 24 23:40:44 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.account
     *
     * @mbggenerated Sun Jun 24 23:40:44 CST 2018
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.exchange_id
     *
     * @mbggenerated Sun Jun 24 23:40:44 CST 2018
     */
    private Integer exchangeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.api_key
     *
     * @mbggenerated Sun Jun 24 23:40:44 CST 2018
     */
    private String apiKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.api_secret
     *
     * @mbggenerated Sun Jun 24 23:40:44 CST 2018
     */
    private String apiSecret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.transaction_secret
     *
     * @mbggenerated Sun Jun 24 23:40:44 CST 2018
     */
    private String transactionSecret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.is_valid
     *
     * @mbggenerated Sun Jun 24 23:40:44 CST 2018
     */
    private Boolean isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.created_at
     *
     * @mbggenerated Sun Jun 24 23:40:44 CST 2018
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.updated_at
     *
     * @mbggenerated Sun Jun 24 23:40:44 CST 2018
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.id
     *
     * @return the value of accounts.id
     *
     * @mbggenerated Sun Jun 24 23:40:44 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.id
     *
     * @param id the value for accounts.id
     *
     * @mbggenerated Sun Jun 24 23:40:44 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.user_id
     *
     * @return the value of accounts.user_id
     *
     * @mbggenerated Sun Jun 24 23:40:44 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.user_id
     *
     * @param userId the value for accounts.user_id
     *
     * @mbggenerated Sun Jun 24 23:40:44 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.account
     *
     * @return the value of accounts.account
     *
     * @mbggenerated Sun Jun 24 23:40:44 CST 2018
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.account
     *
     * @param account the value for accounts.account
     *
     * @mbggenerated Sun Jun 24 23:40:44 CST 2018
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.exchange_id
     *
     * @return the value of accounts.exchange_id
     *
     * @mbggenerated Sun Jun 24 23:40:44 CST 2018
     */
    public Integer getExchangeId() {
        return exchangeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.exchange_id
     *
     * @param exchangeId the value for accounts.exchange_id
     *
     * @mbggenerated Sun Jun 24 23:40:44 CST 2018
     */
    public void setExchangeId(Integer exchangeId) {
        this.exchangeId = exchangeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.api_key
     *
     * @return the value of accounts.api_key
     *
     * @mbggenerated Sun Jun 24 23:40:44 CST 2018
     */
    public String getApiKey() {
        return apiKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.api_key
     *
     * @param apiKey the value for accounts.api_key
     *
     * @mbggenerated Sun Jun 24 23:40:44 CST 2018
     */
    public void setApiKey(String apiKey) {
        this.apiKey = apiKey == null ? null : apiKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.api_secret
     *
     * @return the value of accounts.api_secret
     *
     * @mbggenerated Sun Jun 24 23:40:44 CST 2018
     */
    public String getApiSecret() {
        return apiSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.api_secret
     *
     * @param apiSecret the value for accounts.api_secret
     *
     * @mbggenerated Sun Jun 24 23:40:44 CST 2018
     */
    public void setApiSecret(String apiSecret) {
        this.apiSecret = apiSecret == null ? null : apiSecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.transaction_secret
     *
     * @return the value of accounts.transaction_secret
     *
     * @mbggenerated Sun Jun 24 23:40:44 CST 2018
     */
    public String getTransactionSecret() {
        return transactionSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.transaction_secret
     *
     * @param transactionSecret the value for accounts.transaction_secret
     *
     * @mbggenerated Sun Jun 24 23:40:44 CST 2018
     */
    public void setTransactionSecret(String transactionSecret) {
        this.transactionSecret = transactionSecret == null ? null : transactionSecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.is_valid
     *
     * @return the value of accounts.is_valid
     *
     * @mbggenerated Sun Jun 24 23:40:44 CST 2018
     */
    public Boolean getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.is_valid
     *
     * @param isValid the value for accounts.is_valid
     *
     * @mbggenerated Sun Jun 24 23:40:44 CST 2018
     */
    public void setIsValid(Boolean isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.created_at
     *
     * @return the value of accounts.created_at
     *
     * @mbggenerated Sun Jun 24 23:40:44 CST 2018
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.created_at
     *
     * @param createdAt the value for accounts.created_at
     *
     * @mbggenerated Sun Jun 24 23:40:44 CST 2018
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.updated_at
     *
     * @return the value of accounts.updated_at
     *
     * @mbggenerated Sun Jun 24 23:40:44 CST 2018
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.updated_at
     *
     * @param updatedAt the value for accounts.updated_at
     *
     * @mbggenerated Sun Jun 24 23:40:44 CST 2018
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}