package com.john.silverfox.dal.mybatis.model;

import java.util.Date;

public class Balance {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column balance.id
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column balance.account_id
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	private Long accountId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column balance.currency_name
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	private String currencyName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column balance.amount
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	private Double amount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column balance.created_at
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column balance.updated_at
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	private Date updatedAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column balance.id
	 * @return  the value of balance.id
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column balance.id
	 * @param id  the value for balance.id
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column balance.account_id
	 * @return  the value of balance.account_id
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public Long getAccountId() {
		return accountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column balance.account_id
	 * @param accountId  the value for balance.account_id
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public void setAccountId(Long accountId) {
		this.accountId = accountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column balance.currency_name
	 * @return  the value of balance.currency_name
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public String getCurrencyName() {
		return currencyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column balance.currency_name
	 * @param currencyName  the value for balance.currency_name
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public void setCurrencyName(String currencyName) {
		this.currencyName = currencyName == null ? null : currencyName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column balance.amount
	 * @return  the value of balance.amount
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public Double getAmount() {
		return amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column balance.amount
	 * @param amount  the value for balance.amount
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public void setAmount(Double amount) {
		this.amount = amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column balance.created_at
	 * @return  the value of balance.created_at
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column balance.created_at
	 * @param createdAt  the value for balance.created_at
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column balance.updated_at
	 * @return  the value of balance.updated_at
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column balance.updated_at
	 * @param updatedAt  the value for balance.updated_at
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}
}