package com.john.silverfox.dal.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MyStrategyExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table my_strategies
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table my_strategies
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table my_strategies
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_strategies
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public MyStrategyExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_strategies
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_strategies
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_strategies
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_strategies
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_strategies
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_strategies
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_strategies
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_strategies
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_strategies
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_strategies
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table my_strategies
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andAccountIdIsNull() {
			addCriterion("account_id is null");
			return (Criteria) this;
		}

		public Criteria andAccountIdIsNotNull() {
			addCriterion("account_id is not null");
			return (Criteria) this;
		}

		public Criteria andAccountIdEqualTo(Long value) {
			addCriterion("account_id =", value, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdNotEqualTo(Long value) {
			addCriterion("account_id <>", value, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdGreaterThan(Long value) {
			addCriterion("account_id >", value, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdGreaterThanOrEqualTo(Long value) {
			addCriterion("account_id >=", value, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdLessThan(Long value) {
			addCriterion("account_id <", value, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdLessThanOrEqualTo(Long value) {
			addCriterion("account_id <=", value, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdIn(List<Long> values) {
			addCriterion("account_id in", values, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdNotIn(List<Long> values) {
			addCriterion("account_id not in", values, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdBetween(Long value1, Long value2) {
			addCriterion("account_id between", value1, value2, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdNotBetween(Long value1, Long value2) {
			addCriterion("account_id not between", value1, value2, "accountId");
			return (Criteria) this;
		}

		public Criteria andStrategyIdIsNull() {
			addCriterion("strategy_id is null");
			return (Criteria) this;
		}

		public Criteria andStrategyIdIsNotNull() {
			addCriterion("strategy_id is not null");
			return (Criteria) this;
		}

		public Criteria andStrategyIdEqualTo(Long value) {
			addCriterion("strategy_id =", value, "strategyId");
			return (Criteria) this;
		}

		public Criteria andStrategyIdNotEqualTo(Long value) {
			addCriterion("strategy_id <>", value, "strategyId");
			return (Criteria) this;
		}

		public Criteria andStrategyIdGreaterThan(Long value) {
			addCriterion("strategy_id >", value, "strategyId");
			return (Criteria) this;
		}

		public Criteria andStrategyIdGreaterThanOrEqualTo(Long value) {
			addCriterion("strategy_id >=", value, "strategyId");
			return (Criteria) this;
		}

		public Criteria andStrategyIdLessThan(Long value) {
			addCriterion("strategy_id <", value, "strategyId");
			return (Criteria) this;
		}

		public Criteria andStrategyIdLessThanOrEqualTo(Long value) {
			addCriterion("strategy_id <=", value, "strategyId");
			return (Criteria) this;
		}

		public Criteria andStrategyIdIn(List<Long> values) {
			addCriterion("strategy_id in", values, "strategyId");
			return (Criteria) this;
		}

		public Criteria andStrategyIdNotIn(List<Long> values) {
			addCriterion("strategy_id not in", values, "strategyId");
			return (Criteria) this;
		}

		public Criteria andStrategyIdBetween(Long value1, Long value2) {
			addCriterion("strategy_id between", value1, value2, "strategyId");
			return (Criteria) this;
		}

		public Criteria andStrategyIdNotBetween(Long value1, Long value2) {
			addCriterion("strategy_id not between", value1, value2, "strategyId");
			return (Criteria) this;
		}

		public Criteria andStrategyContentIsNull() {
			addCriterion("strategy_content is null");
			return (Criteria) this;
		}

		public Criteria andStrategyContentIsNotNull() {
			addCriterion("strategy_content is not null");
			return (Criteria) this;
		}

		public Criteria andStrategyContentEqualTo(String value) {
			addCriterion("strategy_content =", value, "strategyContent");
			return (Criteria) this;
		}

		public Criteria andStrategyContentNotEqualTo(String value) {
			addCriterion("strategy_content <>", value, "strategyContent");
			return (Criteria) this;
		}

		public Criteria andStrategyContentGreaterThan(String value) {
			addCriterion("strategy_content >", value, "strategyContent");
			return (Criteria) this;
		}

		public Criteria andStrategyContentGreaterThanOrEqualTo(String value) {
			addCriterion("strategy_content >=", value, "strategyContent");
			return (Criteria) this;
		}

		public Criteria andStrategyContentLessThan(String value) {
			addCriterion("strategy_content <", value, "strategyContent");
			return (Criteria) this;
		}

		public Criteria andStrategyContentLessThanOrEqualTo(String value) {
			addCriterion("strategy_content <=", value, "strategyContent");
			return (Criteria) this;
		}

		public Criteria andStrategyContentLike(String value) {
			addCriterion("strategy_content like", value, "strategyContent");
			return (Criteria) this;
		}

		public Criteria andStrategyContentNotLike(String value) {
			addCriterion("strategy_content not like", value, "strategyContent");
			return (Criteria) this;
		}

		public Criteria andStrategyContentIn(List<String> values) {
			addCriterion("strategy_content in", values, "strategyContent");
			return (Criteria) this;
		}

		public Criteria andStrategyContentNotIn(List<String> values) {
			addCriterion("strategy_content not in", values, "strategyContent");
			return (Criteria) this;
		}

		public Criteria andStrategyContentBetween(String value1, String value2) {
			addCriterion("strategy_content between", value1, value2, "strategyContent");
			return (Criteria) this;
		}

		public Criteria andStrategyContentNotBetween(String value1, String value2) {
			addCriterion("strategy_content not between", value1, value2, "strategyContent");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Integer value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Integer value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Integer value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Integer value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Integer value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Integer> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Integer> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Integer value1, Integer value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andOwnedIsNull() {
			addCriterion("owned is null");
			return (Criteria) this;
		}

		public Criteria andOwnedIsNotNull() {
			addCriterion("owned is not null");
			return (Criteria) this;
		}

		public Criteria andOwnedEqualTo(Boolean value) {
			addCriterion("owned =", value, "owned");
			return (Criteria) this;
		}

		public Criteria andOwnedNotEqualTo(Boolean value) {
			addCriterion("owned <>", value, "owned");
			return (Criteria) this;
		}

		public Criteria andOwnedGreaterThan(Boolean value) {
			addCriterion("owned >", value, "owned");
			return (Criteria) this;
		}

		public Criteria andOwnedGreaterThanOrEqualTo(Boolean value) {
			addCriterion("owned >=", value, "owned");
			return (Criteria) this;
		}

		public Criteria andOwnedLessThan(Boolean value) {
			addCriterion("owned <", value, "owned");
			return (Criteria) this;
		}

		public Criteria andOwnedLessThanOrEqualTo(Boolean value) {
			addCriterion("owned <=", value, "owned");
			return (Criteria) this;
		}

		public Criteria andOwnedIn(List<Boolean> values) {
			addCriterion("owned in", values, "owned");
			return (Criteria) this;
		}

		public Criteria andOwnedNotIn(List<Boolean> values) {
			addCriterion("owned not in", values, "owned");
			return (Criteria) this;
		}

		public Criteria andOwnedBetween(Boolean value1, Boolean value2) {
			addCriterion("owned between", value1, value2, "owned");
			return (Criteria) this;
		}

		public Criteria andOwnedNotBetween(Boolean value1, Boolean value2) {
			addCriterion("owned not between", value1, value2, "owned");
			return (Criteria) this;
		}

		public Criteria andCreatedAtIsNull() {
			addCriterion("created_at is null");
			return (Criteria) this;
		}

		public Criteria andCreatedAtIsNotNull() {
			addCriterion("created_at is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedAtEqualTo(Date value) {
			addCriterion("created_at =", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtNotEqualTo(Date value) {
			addCriterion("created_at <>", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtGreaterThan(Date value) {
			addCriterion("created_at >", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
			addCriterion("created_at >=", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtLessThan(Date value) {
			addCriterion("created_at <", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
			addCriterion("created_at <=", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtIn(List<Date> values) {
			addCriterion("created_at in", values, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtNotIn(List<Date> values) {
			addCriterion("created_at not in", values, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtBetween(Date value1, Date value2) {
			addCriterion("created_at between", value1, value2, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
			addCriterion("created_at not between", value1, value2, "createdAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtIsNull() {
			addCriterion("updated_at is null");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtIsNotNull() {
			addCriterion("updated_at is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtEqualTo(Date value) {
			addCriterion("updated_at =", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtNotEqualTo(Date value) {
			addCriterion("updated_at <>", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtGreaterThan(Date value) {
			addCriterion("updated_at >", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value) {
			addCriterion("updated_at >=", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtLessThan(Date value) {
			addCriterion("updated_at <", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtLessThanOrEqualTo(Date value) {
			addCriterion("updated_at <=", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtIn(List<Date> values) {
			addCriterion("updated_at in", values, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtNotIn(List<Date> values) {
			addCriterion("updated_at not in", values, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtBetween(Date value1, Date value2) {
			addCriterion("updated_at between", value1, value2, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtNotBetween(Date value1, Date value2) {
			addCriterion("updated_at not between", value1, value2, "updatedAt");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table my_strategies
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table my_strategies
     *
     * @mbggenerated do_not_delete_during_merge Fri Jun 22 12:35:01 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}