package com.john.silverfox.dal.mybatis.model;

import java.util.Date;

public class MyStrategy {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column my_strategies.id
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column my_strategies.account_id
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	private Long accountId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column my_strategies.strategy_id
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	private Long strategyId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column my_strategies.strategy_content
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	private String strategyContent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column my_strategies.status
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column my_strategies.owned
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	private Boolean owned;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column my_strategies.created_at
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column my_strategies.updated_at
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	private Date updatedAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column my_strategies.id
	 * @return  the value of my_strategies.id
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column my_strategies.id
	 * @param id  the value for my_strategies.id
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column my_strategies.account_id
	 * @return  the value of my_strategies.account_id
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public Long getAccountId() {
		return accountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column my_strategies.account_id
	 * @param accountId  the value for my_strategies.account_id
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public void setAccountId(Long accountId) {
		this.accountId = accountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column my_strategies.strategy_id
	 * @return  the value of my_strategies.strategy_id
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public Long getStrategyId() {
		return strategyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column my_strategies.strategy_id
	 * @param strategyId  the value for my_strategies.strategy_id
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public void setStrategyId(Long strategyId) {
		this.strategyId = strategyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column my_strategies.strategy_content
	 * @return  the value of my_strategies.strategy_content
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public String getStrategyContent() {
		return strategyContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column my_strategies.strategy_content
	 * @param strategyContent  the value for my_strategies.strategy_content
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public void setStrategyContent(String strategyContent) {
		this.strategyContent = strategyContent == null ? null : strategyContent.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column my_strategies.status
	 * @return  the value of my_strategies.status
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column my_strategies.status
	 * @param status  the value for my_strategies.status
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column my_strategies.owned
	 * @return  the value of my_strategies.owned
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public Boolean getOwned() {
		return owned;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column my_strategies.owned
	 * @param owned  the value for my_strategies.owned
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public void setOwned(Boolean owned) {
		this.owned = owned;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column my_strategies.created_at
	 * @return  the value of my_strategies.created_at
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column my_strategies.created_at
	 * @param createdAt  the value for my_strategies.created_at
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column my_strategies.updated_at
	 * @return  the value of my_strategies.updated_at
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column my_strategies.updated_at
	 * @param updatedAt  the value for my_strategies.updated_at
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}
}