package com.john.silverfox.dal.mybatis.model;

import java.util.Date;

public class Strategy {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column strategies.id
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column strategies.name
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column strategies.remark
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column strategies.strategy_template
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	private String strategyTemplate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column strategies.created_at
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column strategies.updated_at
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	private Date updatedAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column strategies.id
	 * @return  the value of strategies.id
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column strategies.id
	 * @param id  the value for strategies.id
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column strategies.name
	 * @return  the value of strategies.name
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column strategies.name
	 * @param name  the value for strategies.name
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column strategies.remark
	 * @return  the value of strategies.remark
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column strategies.remark
	 * @param remark  the value for strategies.remark
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column strategies.strategy_template
	 * @return  the value of strategies.strategy_template
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public String getStrategyTemplate() {
		return strategyTemplate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column strategies.strategy_template
	 * @param strategyTemplate  the value for strategies.strategy_template
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public void setStrategyTemplate(String strategyTemplate) {
		this.strategyTemplate = strategyTemplate == null ? null : strategyTemplate.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column strategies.created_at
	 * @return  the value of strategies.created_at
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column strategies.created_at
	 * @param createdAt  the value for strategies.created_at
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column strategies.updated_at
	 * @return  the value of strategies.updated_at
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column strategies.updated_at
	 * @param updatedAt  the value for strategies.updated_at
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}
}