package com.john.silverfox.dal.mybatis.model;

import java.util.Date;

public class TickRecord {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tick_records.id
	 * @mbggenerated  Sun Jun 24 23:31:22 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tick_records.tick
	 * @mbggenerated  Sun Jun 24 23:31:22 CST 2018
	 */
	private String tick;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tick_records.currency_pair
	 * @mbggenerated  Sun Jun 24 23:31:22 CST 2018
	 */
	private String currencyPair;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tick_records.rate
	 * @mbggenerated  Sun Jun 24 23:31:22 CST 2018
	 */
	private Double rate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tick_records.exchange_id
	 * @mbggenerated  Sun Jun 24 23:31:22 CST 2018
	 */
	private Integer exchangeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tick_records.trend
	 * @mbggenerated  Sun Jun 24 23:31:22 CST 2018
	 */
	private Integer trend;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tick_records.created_at
	 * @mbggenerated  Sun Jun 24 23:31:22 CST 2018
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tick_records.updated_at
	 * @mbggenerated  Sun Jun 24 23:31:22 CST 2018
	 */
	private Date updatedAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tick_records.id
	 * @return  the value of tick_records.id
	 * @mbggenerated  Sun Jun 24 23:31:22 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tick_records.id
	 * @param id  the value for tick_records.id
	 * @mbggenerated  Sun Jun 24 23:31:22 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tick_records.tick
	 * @return  the value of tick_records.tick
	 * @mbggenerated  Sun Jun 24 23:31:22 CST 2018
	 */
	public String getTick() {
		return tick;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tick_records.tick
	 * @param tick  the value for tick_records.tick
	 * @mbggenerated  Sun Jun 24 23:31:22 CST 2018
	 */
	public void setTick(String tick) {
		this.tick = tick == null ? null : tick.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tick_records.currency_pair
	 * @return  the value of tick_records.currency_pair
	 * @mbggenerated  Sun Jun 24 23:31:22 CST 2018
	 */
	public String getCurrencyPair() {
		return currencyPair;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tick_records.currency_pair
	 * @param currencyPair  the value for tick_records.currency_pair
	 * @mbggenerated  Sun Jun 24 23:31:22 CST 2018
	 */
	public void setCurrencyPair(String currencyPair) {
		this.currencyPair = currencyPair == null ? null : currencyPair.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tick_records.rate
	 * @return  the value of tick_records.rate
	 * @mbggenerated  Sun Jun 24 23:31:22 CST 2018
	 */
	public Double getRate() {
		return rate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tick_records.rate
	 * @param rate  the value for tick_records.rate
	 * @mbggenerated  Sun Jun 24 23:31:22 CST 2018
	 */
	public void setRate(Double rate) {
		this.rate = rate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tick_records.exchange_id
	 * @return  the value of tick_records.exchange_id
	 * @mbggenerated  Sun Jun 24 23:31:22 CST 2018
	 */
	public Integer getExchangeId() {
		return exchangeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tick_records.exchange_id
	 * @param exchangeId  the value for tick_records.exchange_id
	 * @mbggenerated  Sun Jun 24 23:31:22 CST 2018
	 */
	public void setExchangeId(Integer exchangeId) {
		this.exchangeId = exchangeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tick_records.trend
	 * @return  the value of tick_records.trend
	 * @mbggenerated  Sun Jun 24 23:31:22 CST 2018
	 */
	public Integer getTrend() {
		return trend;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tick_records.trend
	 * @param trend  the value for tick_records.trend
	 * @mbggenerated  Sun Jun 24 23:31:22 CST 2018
	 */
	public void setTrend(Integer trend) {
		this.trend = trend;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tick_records.created_at
	 * @return  the value of tick_records.created_at
	 * @mbggenerated  Sun Jun 24 23:31:22 CST 2018
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tick_records.created_at
	 * @param createdAt  the value for tick_records.created_at
	 * @mbggenerated  Sun Jun 24 23:31:22 CST 2018
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tick_records.updated_at
	 * @return  the value of tick_records.updated_at
	 * @mbggenerated  Sun Jun 24 23:31:22 CST 2018
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tick_records.updated_at
	 * @param updatedAt  the value for tick_records.updated_at
	 * @mbggenerated  Sun Jun 24 23:31:22 CST 2018
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}
}