package com.john.silverfox.dal.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TickRecordExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tick_records
	 * @mbggenerated  Sun Jun 24 23:31:22 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tick_records
	 * @mbggenerated  Sun Jun 24 23:31:22 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tick_records
	 * @mbggenerated  Sun Jun 24 23:31:22 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tick_records
	 * @mbggenerated  Sun Jun 24 23:31:22 CST 2018
	 */
	public TickRecordExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tick_records
	 * @mbggenerated  Sun Jun 24 23:31:22 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tick_records
	 * @mbggenerated  Sun Jun 24 23:31:22 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tick_records
	 * @mbggenerated  Sun Jun 24 23:31:22 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tick_records
	 * @mbggenerated  Sun Jun 24 23:31:22 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tick_records
	 * @mbggenerated  Sun Jun 24 23:31:22 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tick_records
	 * @mbggenerated  Sun Jun 24 23:31:22 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tick_records
	 * @mbggenerated  Sun Jun 24 23:31:22 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tick_records
	 * @mbggenerated  Sun Jun 24 23:31:22 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tick_records
	 * @mbggenerated  Sun Jun 24 23:31:22 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tick_records
	 * @mbggenerated  Sun Jun 24 23:31:22 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tick_records
	 * @mbggenerated  Sun Jun 24 23:31:22 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andTickIsNull() {
			addCriterion("tick is null");
			return (Criteria) this;
		}

		public Criteria andTickIsNotNull() {
			addCriterion("tick is not null");
			return (Criteria) this;
		}

		public Criteria andTickEqualTo(String value) {
			addCriterion("tick =", value, "tick");
			return (Criteria) this;
		}

		public Criteria andTickNotEqualTo(String value) {
			addCriterion("tick <>", value, "tick");
			return (Criteria) this;
		}

		public Criteria andTickGreaterThan(String value) {
			addCriterion("tick >", value, "tick");
			return (Criteria) this;
		}

		public Criteria andTickGreaterThanOrEqualTo(String value) {
			addCriterion("tick >=", value, "tick");
			return (Criteria) this;
		}

		public Criteria andTickLessThan(String value) {
			addCriterion("tick <", value, "tick");
			return (Criteria) this;
		}

		public Criteria andTickLessThanOrEqualTo(String value) {
			addCriterion("tick <=", value, "tick");
			return (Criteria) this;
		}

		public Criteria andTickLike(String value) {
			addCriterion("tick like", value, "tick");
			return (Criteria) this;
		}

		public Criteria andTickNotLike(String value) {
			addCriterion("tick not like", value, "tick");
			return (Criteria) this;
		}

		public Criteria andTickIn(List<String> values) {
			addCriterion("tick in", values, "tick");
			return (Criteria) this;
		}

		public Criteria andTickNotIn(List<String> values) {
			addCriterion("tick not in", values, "tick");
			return (Criteria) this;
		}

		public Criteria andTickBetween(String value1, String value2) {
			addCriterion("tick between", value1, value2, "tick");
			return (Criteria) this;
		}

		public Criteria andTickNotBetween(String value1, String value2) {
			addCriterion("tick not between", value1, value2, "tick");
			return (Criteria) this;
		}

		public Criteria andCurrencyPairIsNull() {
			addCriterion("currency_pair is null");
			return (Criteria) this;
		}

		public Criteria andCurrencyPairIsNotNull() {
			addCriterion("currency_pair is not null");
			return (Criteria) this;
		}

		public Criteria andCurrencyPairEqualTo(String value) {
			addCriterion("currency_pair =", value, "currencyPair");
			return (Criteria) this;
		}

		public Criteria andCurrencyPairNotEqualTo(String value) {
			addCriterion("currency_pair <>", value, "currencyPair");
			return (Criteria) this;
		}

		public Criteria andCurrencyPairGreaterThan(String value) {
			addCriterion("currency_pair >", value, "currencyPair");
			return (Criteria) this;
		}

		public Criteria andCurrencyPairGreaterThanOrEqualTo(String value) {
			addCriterion("currency_pair >=", value, "currencyPair");
			return (Criteria) this;
		}

		public Criteria andCurrencyPairLessThan(String value) {
			addCriterion("currency_pair <", value, "currencyPair");
			return (Criteria) this;
		}

		public Criteria andCurrencyPairLessThanOrEqualTo(String value) {
			addCriterion("currency_pair <=", value, "currencyPair");
			return (Criteria) this;
		}

		public Criteria andCurrencyPairLike(String value) {
			addCriterion("currency_pair like", value, "currencyPair");
			return (Criteria) this;
		}

		public Criteria andCurrencyPairNotLike(String value) {
			addCriterion("currency_pair not like", value, "currencyPair");
			return (Criteria) this;
		}

		public Criteria andCurrencyPairIn(List<String> values) {
			addCriterion("currency_pair in", values, "currencyPair");
			return (Criteria) this;
		}

		public Criteria andCurrencyPairNotIn(List<String> values) {
			addCriterion("currency_pair not in", values, "currencyPair");
			return (Criteria) this;
		}

		public Criteria andCurrencyPairBetween(String value1, String value2) {
			addCriterion("currency_pair between", value1, value2, "currencyPair");
			return (Criteria) this;
		}

		public Criteria andCurrencyPairNotBetween(String value1, String value2) {
			addCriterion("currency_pair not between", value1, value2, "currencyPair");
			return (Criteria) this;
		}

		public Criteria andRateIsNull() {
			addCriterion("rate is null");
			return (Criteria) this;
		}

		public Criteria andRateIsNotNull() {
			addCriterion("rate is not null");
			return (Criteria) this;
		}

		public Criteria andRateEqualTo(Double value) {
			addCriterion("rate =", value, "rate");
			return (Criteria) this;
		}

		public Criteria andRateNotEqualTo(Double value) {
			addCriterion("rate <>", value, "rate");
			return (Criteria) this;
		}

		public Criteria andRateGreaterThan(Double value) {
			addCriterion("rate >", value, "rate");
			return (Criteria) this;
		}

		public Criteria andRateGreaterThanOrEqualTo(Double value) {
			addCriterion("rate >=", value, "rate");
			return (Criteria) this;
		}

		public Criteria andRateLessThan(Double value) {
			addCriterion("rate <", value, "rate");
			return (Criteria) this;
		}

		public Criteria andRateLessThanOrEqualTo(Double value) {
			addCriterion("rate <=", value, "rate");
			return (Criteria) this;
		}

		public Criteria andRateIn(List<Double> values) {
			addCriterion("rate in", values, "rate");
			return (Criteria) this;
		}

		public Criteria andRateNotIn(List<Double> values) {
			addCriterion("rate not in", values, "rate");
			return (Criteria) this;
		}

		public Criteria andRateBetween(Double value1, Double value2) {
			addCriterion("rate between", value1, value2, "rate");
			return (Criteria) this;
		}

		public Criteria andRateNotBetween(Double value1, Double value2) {
			addCriterion("rate not between", value1, value2, "rate");
			return (Criteria) this;
		}

		public Criteria andExchangeIdIsNull() {
			addCriterion("exchange_id is null");
			return (Criteria) this;
		}

		public Criteria andExchangeIdIsNotNull() {
			addCriterion("exchange_id is not null");
			return (Criteria) this;
		}

		public Criteria andExchangeIdEqualTo(Integer value) {
			addCriterion("exchange_id =", value, "exchangeId");
			return (Criteria) this;
		}

		public Criteria andExchangeIdNotEqualTo(Integer value) {
			addCriterion("exchange_id <>", value, "exchangeId");
			return (Criteria) this;
		}

		public Criteria andExchangeIdGreaterThan(Integer value) {
			addCriterion("exchange_id >", value, "exchangeId");
			return (Criteria) this;
		}

		public Criteria andExchangeIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("exchange_id >=", value, "exchangeId");
			return (Criteria) this;
		}

		public Criteria andExchangeIdLessThan(Integer value) {
			addCriterion("exchange_id <", value, "exchangeId");
			return (Criteria) this;
		}

		public Criteria andExchangeIdLessThanOrEqualTo(Integer value) {
			addCriterion("exchange_id <=", value, "exchangeId");
			return (Criteria) this;
		}

		public Criteria andExchangeIdIn(List<Integer> values) {
			addCriterion("exchange_id in", values, "exchangeId");
			return (Criteria) this;
		}

		public Criteria andExchangeIdNotIn(List<Integer> values) {
			addCriterion("exchange_id not in", values, "exchangeId");
			return (Criteria) this;
		}

		public Criteria andExchangeIdBetween(Integer value1, Integer value2) {
			addCriterion("exchange_id between", value1, value2, "exchangeId");
			return (Criteria) this;
		}

		public Criteria andExchangeIdNotBetween(Integer value1, Integer value2) {
			addCriterion("exchange_id not between", value1, value2, "exchangeId");
			return (Criteria) this;
		}

		public Criteria andTrendIsNull() {
			addCriterion("trend is null");
			return (Criteria) this;
		}

		public Criteria andTrendIsNotNull() {
			addCriterion("trend is not null");
			return (Criteria) this;
		}

		public Criteria andTrendEqualTo(Integer value) {
			addCriterion("trend =", value, "trend");
			return (Criteria) this;
		}

		public Criteria andTrendNotEqualTo(Integer value) {
			addCriterion("trend <>", value, "trend");
			return (Criteria) this;
		}

		public Criteria andTrendGreaterThan(Integer value) {
			addCriterion("trend >", value, "trend");
			return (Criteria) this;
		}

		public Criteria andTrendGreaterThanOrEqualTo(Integer value) {
			addCriterion("trend >=", value, "trend");
			return (Criteria) this;
		}

		public Criteria andTrendLessThan(Integer value) {
			addCriterion("trend <", value, "trend");
			return (Criteria) this;
		}

		public Criteria andTrendLessThanOrEqualTo(Integer value) {
			addCriterion("trend <=", value, "trend");
			return (Criteria) this;
		}

		public Criteria andTrendIn(List<Integer> values) {
			addCriterion("trend in", values, "trend");
			return (Criteria) this;
		}

		public Criteria andTrendNotIn(List<Integer> values) {
			addCriterion("trend not in", values, "trend");
			return (Criteria) this;
		}

		public Criteria andTrendBetween(Integer value1, Integer value2) {
			addCriterion("trend between", value1, value2, "trend");
			return (Criteria) this;
		}

		public Criteria andTrendNotBetween(Integer value1, Integer value2) {
			addCriterion("trend not between", value1, value2, "trend");
			return (Criteria) this;
		}

		public Criteria andCreatedAtIsNull() {
			addCriterion("created_at is null");
			return (Criteria) this;
		}

		public Criteria andCreatedAtIsNotNull() {
			addCriterion("created_at is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedAtEqualTo(Date value) {
			addCriterion("created_at =", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtNotEqualTo(Date value) {
			addCriterion("created_at <>", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtGreaterThan(Date value) {
			addCriterion("created_at >", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
			addCriterion("created_at >=", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtLessThan(Date value) {
			addCriterion("created_at <", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
			addCriterion("created_at <=", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtIn(List<Date> values) {
			addCriterion("created_at in", values, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtNotIn(List<Date> values) {
			addCriterion("created_at not in", values, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtBetween(Date value1, Date value2) {
			addCriterion("created_at between", value1, value2, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
			addCriterion("created_at not between", value1, value2, "createdAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtIsNull() {
			addCriterion("updated_at is null");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtIsNotNull() {
			addCriterion("updated_at is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtEqualTo(Date value) {
			addCriterion("updated_at =", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtNotEqualTo(Date value) {
			addCriterion("updated_at <>", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtGreaterThan(Date value) {
			addCriterion("updated_at >", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value) {
			addCriterion("updated_at >=", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtLessThan(Date value) {
			addCriterion("updated_at <", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtLessThanOrEqualTo(Date value) {
			addCriterion("updated_at <=", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtIn(List<Date> values) {
			addCriterion("updated_at in", values, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtNotIn(List<Date> values) {
			addCriterion("updated_at not in", values, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtBetween(Date value1, Date value2) {
			addCriterion("updated_at between", value1, value2, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtNotBetween(Date value1, Date value2) {
			addCriterion("updated_at not between", value1, value2, "updatedAt");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tick_records
	 * @mbggenerated  Sun Jun 24 23:31:22 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tick_records
     *
     * @mbggenerated do_not_delete_during_merge Fri Jun 22 12:35:01 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}