package com.john.silverfox.dal.mybatis.model;

import java.util.Date;

public class ToTick {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column to_ticks.id
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column to_ticks.currency_pair
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	private String currencyPair;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column to_ticks.is_valid
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	private Boolean isValid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column to_ticks.created_at
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column to_ticks.updated_at
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	private Date updatedAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column to_ticks.id
	 * @return  the value of to_ticks.id
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column to_ticks.id
	 * @param id  the value for to_ticks.id
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column to_ticks.currency_pair
	 * @return  the value of to_ticks.currency_pair
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public String getCurrencyPair() {
		return currencyPair;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column to_ticks.currency_pair
	 * @param currencyPair  the value for to_ticks.currency_pair
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public void setCurrencyPair(String currencyPair) {
		this.currencyPair = currencyPair == null ? null : currencyPair.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column to_ticks.is_valid
	 * @return  the value of to_ticks.is_valid
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public Boolean getIsValid() {
		return isValid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column to_ticks.is_valid
	 * @param isValid  the value for to_ticks.is_valid
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public void setIsValid(Boolean isValid) {
		this.isValid = isValid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column to_ticks.created_at
	 * @return  the value of to_ticks.created_at
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column to_ticks.created_at
	 * @param createdAt  the value for to_ticks.created_at
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column to_ticks.updated_at
	 * @return  the value of to_ticks.updated_at
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column to_ticks.updated_at
	 * @param updatedAt  the value for to_ticks.updated_at
	 * @mbggenerated  Sun Jun 24 22:48:56 CST 2018
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}
}