package com.john.silverfox.dal.mybatis.model;

import java.util.Date;

public class Transaction {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transactions.id
	 * @mbggenerated  Sun Jun 24 23:11:35 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transactions.tick
	 * @mbggenerated  Sun Jun 24 23:11:35 CST 2018
	 */
	private String tick;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transactions.account_id
	 * @mbggenerated  Sun Jun 24 23:11:35 CST 2018
	 */
	private Long accountId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transactions.type
	 * @mbggenerated  Sun Jun 24 23:11:35 CST 2018
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transactions.currency_pair
	 * @mbggenerated  Sun Jun 24 23:11:35 CST 2018
	 */
	private String currencyPair;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transactions.rate
	 * @mbggenerated  Sun Jun 24 23:11:35 CST 2018
	 */
	private Double rate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transactions.amount
	 * @mbggenerated  Sun Jun 24 23:11:35 CST 2018
	 */
	private Double amount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transactions.status
	 * @mbggenerated  Sun Jun 24 23:11:35 CST 2018
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transactions.created_at
	 * @mbggenerated  Sun Jun 24 23:11:35 CST 2018
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transactions.updated_at
	 * @mbggenerated  Sun Jun 24 23:11:35 CST 2018
	 */
	private Date updatedAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transactions.id
	 * @return  the value of transactions.id
	 * @mbggenerated  Sun Jun 24 23:11:35 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transactions.id
	 * @param id  the value for transactions.id
	 * @mbggenerated  Sun Jun 24 23:11:35 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transactions.tick
	 * @return  the value of transactions.tick
	 * @mbggenerated  Sun Jun 24 23:11:35 CST 2018
	 */
	public String getTick() {
		return tick;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transactions.tick
	 * @param tick  the value for transactions.tick
	 * @mbggenerated  Sun Jun 24 23:11:35 CST 2018
	 */
	public void setTick(String tick) {
		this.tick = tick == null ? null : tick.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transactions.account_id
	 * @return  the value of transactions.account_id
	 * @mbggenerated  Sun Jun 24 23:11:35 CST 2018
	 */
	public Long getAccountId() {
		return accountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transactions.account_id
	 * @param accountId  the value for transactions.account_id
	 * @mbggenerated  Sun Jun 24 23:11:35 CST 2018
	 */
	public void setAccountId(Long accountId) {
		this.accountId = accountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transactions.type
	 * @return  the value of transactions.type
	 * @mbggenerated  Sun Jun 24 23:11:35 CST 2018
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transactions.type
	 * @param type  the value for transactions.type
	 * @mbggenerated  Sun Jun 24 23:11:35 CST 2018
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transactions.currency_pair
	 * @return  the value of transactions.currency_pair
	 * @mbggenerated  Sun Jun 24 23:11:35 CST 2018
	 */
	public String getCurrencyPair() {
		return currencyPair;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transactions.currency_pair
	 * @param currencyPair  the value for transactions.currency_pair
	 * @mbggenerated  Sun Jun 24 23:11:35 CST 2018
	 */
	public void setCurrencyPair(String currencyPair) {
		this.currencyPair = currencyPair == null ? null : currencyPair.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transactions.rate
	 * @return  the value of transactions.rate
	 * @mbggenerated  Sun Jun 24 23:11:35 CST 2018
	 */
	public Double getRate() {
		return rate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transactions.rate
	 * @param rate  the value for transactions.rate
	 * @mbggenerated  Sun Jun 24 23:11:35 CST 2018
	 */
	public void setRate(Double rate) {
		this.rate = rate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transactions.amount
	 * @return  the value of transactions.amount
	 * @mbggenerated  Sun Jun 24 23:11:35 CST 2018
	 */
	public Double getAmount() {
		return amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transactions.amount
	 * @param amount  the value for transactions.amount
	 * @mbggenerated  Sun Jun 24 23:11:35 CST 2018
	 */
	public void setAmount(Double amount) {
		this.amount = amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transactions.status
	 * @return  the value of transactions.status
	 * @mbggenerated  Sun Jun 24 23:11:35 CST 2018
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transactions.status
	 * @param status  the value for transactions.status
	 * @mbggenerated  Sun Jun 24 23:11:35 CST 2018
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transactions.created_at
	 * @return  the value of transactions.created_at
	 * @mbggenerated  Sun Jun 24 23:11:35 CST 2018
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transactions.created_at
	 * @param createdAt  the value for transactions.created_at
	 * @mbggenerated  Sun Jun 24 23:11:35 CST 2018
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transactions.updated_at
	 * @return  the value of transactions.updated_at
	 * @mbggenerated  Sun Jun 24 23:11:35 CST 2018
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transactions.updated_at
	 * @param updatedAt  the value for transactions.updated_at
	 * @mbggenerated  Sun Jun 24 23:11:35 CST 2018
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}
}